name: Arcade
version: 1.0
description: Blockcade Arcade Core
api-version: 1.13
main: net.blockcade.Arcade.Main
load: STARTUP
commands:
  mct:
    description: Map Creator Tools
  debug:
    description: Debugging command
loadbefore:
  - PIT
  - BedBattles
  - CTF